openapi: 3.0.0
info:
  title: PolyDrive API
  description: API for the awesome PolyDrive project!
  version: 0.0.1
servers:
  - url: 'http://api.example.com/v1'
    description: test server
paths:
  /res:
    get:
      tags:
        - resources
      summary: Return root content.
      description: >-
        Return the list of all user's resources with no parent. Content is
        recursive.
      responses:
        '200':
          description: List of resources.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Resource'
  '/res/{res_id}':
    parameters:
      - $ref: '#/components/parameters/res_id'
    get:
      tags:
        - resources
      summary: Return resource's details.
      description: >-
        Return the details of the specified resource. If the resource is a
        folder, return its recursive content.
      responses:
        '200':
          description: List of resources.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Resource'
        '404':
          $ref: '#/components/responses/NotFound'
  /login:
    post:
      tags:
        - users
      summary: Log a user in.
      description: Authenticate the user when valid credentials are submitted.
      responses:
        '200':
          description: Object describing the logged user.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  parameters:
    res_id:
      name: res_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
      description: The resource's identifier
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
        status:
          type: string
        messages:
          type: array
          items:
            type: string
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
    Resource:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        extension:
          type: string
        mime:
          type: string
        type:
          type: string
          enum:
            - file
            - folder
        owner:
          $ref: '#/components/schemas/User'
  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
    Unauthorized:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
